### ISSUE TITLE
Consider having one component for all bar settings

### ISSUE THREAD

**Issue by 5tr1k3r** [sparten11740/bevy_health_bar3d#27]
I could be overthinking this, but it feels like having one component for all bar settings (instead of current `BarBundle`) could lead to a nicer API.
- there would be less of a visual pollution in the inspector
- this gets especially bad if there are multiple bars
- I'm looking into adding one more bar setting (BarVisibility), which would have further negative impact

There is also a related issue of how these component settings don't do anything after the bar is already spawned. So could either:
- rework things so it's possible to update bar settings by changing the correspondent components
- despawn all of the `BarBundle` components after the bar is spawned

**Comment by sparten11740** [comment]
I like the idea of having one settings component instead of many. There's not really a case for applying these components elsewhere anyway. 

> how these component settings don't do anything after the bar is already spawned

yeah, a system that updates the material when settings are changed was something I have in my todos but didn't get to yet. If we have one settings component, change detection would trigger for a change to any of its fields, not sure if that will have any implications, probably not.
